### ISSUE TITLE
Assumes python installer is pre-installed

### ISSUE THREAD

**Issue by martinkearn** [masoncusack/SimpleAzureSearch#1]
The instructions assume that the Python installer is already installed to enable the `pip3` command,

It may be worth calling that out in the `readme.md` to ensure a friction-free install.

#BeingPedantic

#Sorry

**Comment by masoncusack** [comment]
Hi Martin. I thought about this but left it down to Googling/knowing Python basics. I've addressed it in the [latest commit](https://github.com/masoncusack/SimpleAzureSearch/commit/2a04dae8ab730f475aaf9cbe00b316aa70b128ec) by adding prerequisites to the README. Can you let me know if that solves your issue?

**Comment by martinkearn** [comment]
Yes, the readme looks clearer now. thanks
