### ISSUE TITLE
Some search results do not have an ID - including samples

### ISSUE THREAD

**Issue by martinkearn** [masoncusack/SimpleAzureSearch#2]
On line 43 of ui.py, it assumes that the result has a key called `Id`.

Certainly some data sets will not have this key as it is not required by Azure Cognitive Search. The samples included with Azure Cognitive Search do not have a key called `Id`..

If the key is missing it causes an error
![image](https://user-images.githubusercontent.com/2410726/105000413-333fac00-5a26-11eb-839b-03edb5a307f2.png)

Would it be better to write out the first key rather than hard-coding `Id`? That way you know it will always write something and will make for a more friction-less demo. In many cases, the first key is some kind of Id anyway, in the case of the hotels sample dataset, it is called `HotelId`.

#BeingPedantic

#Sorry

**Comment by masoncusack** [comment]
Hi Martin. Good idea. I've addressed this in the [latest commit](https://github.com/masoncusack/SimpleAzureSearch/commit/2a04dae8ab730f475aaf9cbe00b316aa70b128ec). Can you let me know if that solves your issue?

**Comment by martinkearn** [comment]
Yes, this "just works" now and should do with almost any search index.
